"""Initial migration

Revision ID: 2ea03660eeef
Revises: 
Create Date: 2025-12-08 20:53:43.270510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea03660eeef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_salaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_no', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['employee_no'], ['employees.employee_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employee_titles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_titles',
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('title', name=op.f('employee_titles_pkey'))
    )
    op.drop_table('employee_salaries')
    # ### end Alembic commands ###
